import { ThemeProvider } from "components/theme-provider"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { SystemProvider } from "service/system"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SystemProvider>{children}</SystemProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
